services:
    local:
        container_name: refresh-databases_local
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
        tty: true
        stdin_open: true
        depends_on:
            - test-mysql

    test-mysql:
        container_name: refresh-databases_test-mysql
        image: mysql:8.0
        volumes:
            - ./docker/create-databases.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=laravel
        ports:
            - 13306:3306
